Bugfix/db init
fac30/things-we-do pull request #37
Opened 2024-12-03 16:40 UTC by jackcasstlesjones

# What type of PR is this? (check all applicable)

# POTENTIALLY BREAKING CHANGE. PLEASE DO NOT MERGE UNTIL BOTH @JasonWarrenUK AND @maxitect HAVE REVIEWED.

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Styling
- [ ] Build
- [ ] Chore

## Description

- Wrapped db logic in a class to prevent errors from constant initialisation - previous `if` statement to check if db existed was not doing the job. Db was attempting to be initialised on page refresh and erroring.
- Had to comment out a lot of `addTool` with jason's permission

## Screenshots

_Please replace this line with any relevant images for UI changes._

## UI accessibility checklist

_If your PR includes UI changes, please utilize this checklist:_

- [ ] Semantic HTML implemented?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Added/updated tests?

_Please aim to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Delete branch after merge?

- [ ] Yes
- [ ] No

## What gif best describes this PR or how it makes you feel?

![alt_text](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExODA5NTJ0aXM5dGVkZm8xNHJoMjV4dzQ3OXVydjlxdmc2Mmw2aTRpeCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/9M5jK4GXmD5o1irGrF/giphy.gif)

2024-12-03 22:30 UTC, maxitect requested changes
This is really neat, having all database methods within a class is a good move - OOP FTW!
Couple of comments, one I won't let go to do with accessibility (even if it is for testing purposes), the other a bit more open we can probably discuss tomorrow.
Other than that, I have reviewed all the code here, tested the functionality in the deployment preview, tested that it reads and writes to the collections in my local storage, everything works fine for me.

PS: unclear why so much of the add tool code had to be commented out but we can review that tomorrow

2024-12-03 22:30 UTC, maxitect commented on src/app/insights/components/InsightsDisplay.tsx
> +        <h1>No insights available</h1>
```suggestion
            <p>dopamine: {insight.neurotransmitters.dopamine}</p>
            <p>serotonin: {insight.neurotransmitters.serotonin}</p>
            <p>adrenaline: {insight.neurotransmitters.adrenaline}</p>
          </div>
        ))
      ) : (
        <p>No insights available</p>
```
I know this is just for testing (and it works, I tested it in the deployed preview) but does not have to be offensively not accessible! xD

2024-12-03 22:30 UTC, maxitect commented on src/lib/db/DatabaseManager.ts
> +  dbInstance: RxDatabase | null = null;
I think this should be inside a constructor method if this is a class? And if not, why?

2024-12-04 10:04 UTC, JasonWarrenUK approved these changes

2024-12-04 10:09 UTC, gurtatiLND approved these changes

2024-12-04 10:10 UTC, maxitect approved these changes
Yay!

2024-12-04 10:10 UTC, merged